const GENERAL_CONSTANTS = {
  SORT: {
    REPORT: 'REPORT',
    LIKE: 'LIKE',

    COMMENT: 'COMMENT',
    POSTID: 'POSTID',
    POST: 'POST',
    EMAIL: 'EMAIL',
    USERID: 'USERID',
    STATUS: 'STATUS',
    FULLNAME: 'FULLNAME',
    FOLLOWING: 'FOLLOWING',
    FOLLOWED: 'FOLLOWED',
  },
  TYPE_NOTIFICATION: {
    LIKE: 'LIKE',
    COMMENT: 'COMMENT',
  },
  STATE_MEMBER: {
    APPROVED: 'APPROVED',
    PENDING: 'PENDING',
    REJECTED: 'REJECTED',
    BANNED: 'BANNED',
  },
};
export default GENERAL_CONSTANTS;
