module.exports = {
  SORT: {
    REPORT: 'REPORT',
    LIKE: 'LIKE',
    COMMENT: 'COMMENT',
    POSTID: 'POSTID',
    POST: 'POST',
    USERID: 'USERID',
    STATUS: 'STATUS',
    FULLNAME: 'FULLNAME',
    FOLLOWING: 'FOLLOWING',
    FOLLOWED: 'FOLLOWED',
  },
  STATE_MEMBER: {
    APPROVED: 'APPROVED',
    PENDING: 'PENDING',
    REJECTED: 'REJECTED',
    BANNED: 'BANNED',
  },
  STATE_POST: {
    APPROVED: 'APPROVED',
    PENDING: 'PENDING',
    REJECTED: 'REJECTED',
    BANNED: 'BANNED',
  },
  STATE_GROUP: {
    ACTIVATED: 'ACTIVATED',
    INACTIVATED: 'INACTIVATED',
  },
  TYPE_GROUP: {
    APPROVED: 'APPROVED',
    FREE: 'FREE',
  },
};
